/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('./components/Avatar.vue')['default']
    BaseStatus: typeof import('./components/BaseStatus.vue')['default']
    CharacterSwitcher: typeof import('./components/CharacterSwitcher.vue')['default']
    MissionStat: typeof import('./components/MissionStat.vue')['default']
    OptionsAccount: typeof import('./components/OptionsAccount.vue')['default']
    OptionsSection: typeof import('./components/OptionsSection.vue')['default']
    OptionsSettings: typeof import('./components/OptionsSettings.vue')['default']
    PopupFooter: typeof import('./components/PopupFooter.vue')['default']
    PopupSection: typeof import('./components/PopupSection.vue')['default']
    Recruit: typeof import('./components/Recruit.vue')['default']
    RhodesIslandManage: typeof import('./components/RhodesIslandManage.vue')['default']
  }
}
