export const ACCOUNTS_KEY = 'local:accounts'
export const AUTHORIZE_KEY_MAPPING = 'local:authorize-mapping'
export const CURRENT_ACCOUNT_KEY = 'local:current-account'
export const CHARARCTER_UID = 'local:chararcter-uid'
export const CHARARCTER_INFO = 'local:chararcter-info'
