export const ACCOUNTS_KEY = 'local:accounts'
export const AUTHORIZE_MAPPING_KEY = 'local:authorize-mapping'
export const CURRENT_ACCOUNT_KEY = 'local:current-account'
export const CHARARCTER_UID_KEY = 'local:chararcter-uid'
export const CHARARCTER_INFO_KEY = 'local:chararcter-info'
export const PREFERENCE_KEY = 'local:preference'
